PAYMENT_METHODS = (
    ("cash", "Наличные"),
    ("card", "Банковская карта"),
)


DRIVER_PHOTO_UPLOAD_TO = "driver_avatars/"
DEFAULT_DRIVER_PHOTO = DRIVER_PHOTO_UPLOAD_TO + "driver_avatar.png"


EXCLUDED_PERMISSION_FROM_ADMIN_FORM = (
    "add_logentry",
    "change_logentry",
    "delete_logentry",
    "view_logentry",
    "add_group",
    "change_group",
    "delete_group",
    "view_group",
    "add_permission",
    "change_permission",
    "delete_permission",
    "view_permission",
    "add_token",
    "change_token",
    "delete_token",
    "view_token",
    "add_tokenproxy",
    "change_tokenproxy",
    "delete_tokenproxy",
    "view_tokenproxy",
    "add_contenttype",
    "change_contenttype",
    "delete_contenttype",
    "view_contenttype",
    "add_session",
    "change_session",
    "delete_session",
    "view_session",
    "add_balance",
    "delete_balance",
    "view_balance",
    "add_car",
    "change_car",
    "delete_car",
    "view_car",
    "add_carbrand",
    "change_carbrand",
    "delete_carbrand",
    "view_carbrand",
    "add_driver",
    "view_driver",
    "add_settings",
    "delete_settings",
    "view_settings",
    "add_authtoken",
    "change_authtoken",
    "delete_authtoken",
    "view_authtoken",
    "add_telegramdata",
    "delete_telegramdata",
    "view_telegramdata",
    "add_user",
    "add_workdriverday",
    "change_workdriverday",
    "delete_workdriverday",
    "view_workdriverday",
    "add_address",
    "change_address",
    "delete_address",
    "view_address",
    "add_costperbabychair",
    "view_costperbabychair",
    "delete_costperbabychair",
    "add_costperkm",
    "view_costperkm",
    "delete_costperkm",
    "change_raffle",
    "delete_raffle",
    "add_order",
    "change_order",
    "delete_order",
    "delete_ban",
    "view_ban",
    "add_telegramauthtoken",
    "change_telegramauthtoken",
    "delete_telegramauthtoken",
    "view_telegramauthtoken",
)

DISPLAY_NAMES_OF_PERMISSIONS = (
    ("change_balance", "Может изменять баланс"),
    ("add_ban", "Может блокировать пользователей"),
    ("delete_ban", "Может снимать блокировку пользователей"),
    ("change_driver", "Может изменять водительские данные"),
    ("delete_driver", "Может лишить статуса водителя"),
    ("change_user", "Может изменять данные о пользователях"),
    ("delete_user", "Может удалять пользователей"),
    ("view_user", "Может просматривать список пользователей"),
    ("add_city", "Может добавлять регистрировать новые города"),
    ("change_city", "Может изменять данные о городах"),
    ("delete_city", "Может удалять города"),
    ("view_city", "Может просматривать список городов"),
    ("change_costperkm", "Может изменять стоимость за километр"),
    ("change_costperbabychair", "Может изменять стоимость за детское кресло"),
    ("add_coupon", "Может создавать купоны"),
    ("change_coupon", "Может изменять купоны"),
    ("delete_coupon", "Может удалять купоны"),
    ("view_coupon", "Может просматривать список купонов"),
    ("add_mailing", "Может создавать рассылки"),
    ("change_mailing", "Может изменять рассылки"),
    ("delete_mailing", "Может удалять рассылки"),
    ("view_mailing", "Может просматривать список рассылок"),
    ("add_message", "Может создавать сообщения"),
    ("change_message", "Может изменять сообщения"),
    ("delete_message", "Может удалять сообщения"),
    ("view_message", "Может просматривать список сообщений"),
    ("add_raffle", "Может проводить розыгрыши"),
    ("view_raffle", "Может просматривать список розыгрышей"),
    ("view_order", "Может просматривать подробную информацию о заказе"),
)
