# Generated by Django 3.1.3 on 2021-06-10 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(verbose_name="Количество бонусов/дней"),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название купона"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный код для купона, например: SALE2021. Максимальное количество символов: 30",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bonuses", "Купон на бонусы"),
                            ("discount", "Купон на скидку на поездку"),
                            ("free_days_driver", "Купон на пробный период"),
                        ],
                        max_length=20,
                        verbose_name="Тип купона",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество купонов"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Дата, до которой нельзя будет получить купон",
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="Дата, после которой нельзя будет получить купон",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "is_disposable",
                    models.BooleanField(
                        default=False,
                        help_text="Если да, то купон можно получить только 1 раз. Если нет, то после использования, можно будет снова получить купон.",
                        verbose_name="Одноразовый ли купон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Купон",
                "verbose_name_plural": "Купоны",
                "ordering": ("-start_date",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=4096, verbose_name="Текст")),
                (
                    "disable_notification",
                    models.BooleanField(
                        default=False,
                        verbose_name="Отключить уведомления у получателей",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фото"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Видео"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="Raffle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название розыгрыша"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата проведения розыгрыша"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referral.coupon",
                        verbose_name="Купон, который получит победитель",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="referral.message",
                        verbose_name="Сообщение победителю",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raffle_wins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розыгрыш",
                "verbose_name_plural": "Розыгрыши",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "mailing_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Если оставить это поле пустым, то рассылка начнётся сразу же после создания. Время по МСК!",
                        null=True,
                        verbose_name="Дата и время рассылки",
                    ),
                ),
                (
                    "user_group",
                    models.IntegerField(
                        choices=[
                            (1, "Все пользователи"),
                            (2, "Водители"),
                            (3, "Клиенты"),
                            (4, "Администраторы"),
                        ],
                        verbose_name="Группа пользователей, которая получит сообщение",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Ожидается"),
                            (2, "Рассылка началась"),
                            (3, "Рассылка окончена"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referral.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status", "-mailing_date"],
            },
        ),
    ]
