# Generated by Django 3.1.3 on 2021-07-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0002_auto_20210704_1922"),
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Present",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Подарок будет выдаваться только клиентам, которые закончили поездку в данном городе.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presents",
                        to="dispatcher.city",
                        verbose_name="Город, в котором будет действовать подарок",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="referral.message",
                        verbose_name="Сообщение с призом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подарок",
                "verbose_name_plural": "Подарки",
            },
        ),
    ]
