# Generated by Django 3.1.3 on 2021-06-10 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cabinet", "0001_initial"),
        ("dispatcher", "0001_initial"),
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="hirer_coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hirer_coupons",
                to="referral.coupon",
                verbose_name="Купон, который выдается приглашенному при регистрации",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="mentor_coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mentor_coupons",
                to="referral.coupon",
                verbose_name="Купон, который выдается ментору за приглашение",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="mentor_coupon_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mentor_coupons_2",
                to="referral.coupon",
                verbose_name="Купон, который выдается ментору, если водитель вышел на линию 7 раз.",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="message_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_1",
                to="referral.message",
                verbose_name="Сообщение, которое отправляется пользователям, которые 5 дней не делали заказ",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="message_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_2",
                to="referral.message",
                verbose_name="Сообщение, которое отправляется водителям, когда кончаются бесплатные дни",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="car",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver",
                to="cabinet.car",
                verbose_name="Автомобиль",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cabinet.carbrand",
                verbose_name="Марка автомобиля",
            ),
        ),
        migrations.AddField(
            model_name="ban",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="coupons",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="referral.Coupon",
                verbose_name="Промокоды",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="driver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cabinet.driver",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="dispatcher.location",
                verbose_name="Местоположение пользователя",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="heirs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ментор (пригласивший)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="used_coupons",
            field=models.ManyToManyField(
                blank=True,
                related_name="used_users",
                to="referral.Coupon",
                verbose_name="Использованные промокоды",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
    ]
