# Generated by Django 3.2 on 2022-07-02 12:01

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0004_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="web_app_map_center",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(59.93521, 30.316447),
                srid=4326,
                verbose_name="Начальная точка на карте",
            ),
        ),
    ]
