apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: docker-repo/core:build-${BUILD_ID}
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: core-config
        - secretRef:
            name: core-secrets
        volumeMounts:
        - name: core-storage
          mountPath: /app/core/
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: core-storage
        persistentVolumeClaim:
          claimName: core-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  selector:
    app: core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
