apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot
        image: docker-repo/telegram-bot:build-${BUILD_ID}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: telegram-bot-config
        - secretRef:
            name: telegram-bot-secrets
        volumeMounts:
        - name: telegram-bot-storage
          mountPath: /app/telegram_bot/
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: telegram-bot-storage
        persistentVolumeClaim:
          claimName: telegram-bot-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
spec:
  selector:
    app: telegram-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
