# Generated by Django 3.1.3 on 2021-07-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="search_drivers_radius",
            field=models.IntegerField(
                blank=True,
                help_text="Указывается в метрах. Если не указан, то будет применён радиус 30000м.",
                null=True,
                verbose_name="Радиус поиска водителей",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="finish_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finish_addresses",
                to="dispatcher.address",
                verbose_name="Адрес точки прибытия",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="place_id",
            field=models.BigIntegerField(
                primary_key=True,
                serialize=False,
                verbose_name="Уникальный идентификатор местоположения",
            ),
        ),
        migrations.CreateModel(
            name="OrderRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="dispatcher.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказы, которые нужно перепроверить",
                "verbose_name_plural": "Заказы, которые нужно перепроверить",
            },
        ),
    ]
