# Generated by Django 3.1.3 on 2021-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0002_auto_20210704_1922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="house_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=16,
                null=True,
                verbose_name="Номер дома",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="place_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="road",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=256,
                null=True,
                verbose_name="Улица",
            ),
        ),
    ]
