# Generated by Django 3.1.3 on 2021-10-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0003_auto_20211021_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="place_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
