# Generated by Django 3.2 on 2022-07-02 12:09

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0005_auto_20220514_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="web_app_map_center",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(30.316447, 59.93521),
                srid=4326,
                verbose_name="Начальная точка на карте",
            ),
        ),
    ]
