# Generated by Django 3.2 on 2022-07-09 13:51

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0006_settings_web_app_map_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="waiting_free_minutes",
            field=models.PositiveIntegerField(
                default=3, verbose_name="Бесплатные минуты ожидания"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="web_app_map_center",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(59.93521, 30.316447),
                srid=4326,
                verbose_name="Начальная точка на карте",
            ),
        ),
    ]
