# Generated by Django 3.2 on 2022-07-10 12:08

import cabinet.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0007_auto_20220709_1651"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="waiting_price",
            field=cabinet.fields.MoneyField(
                decimal_places=2,
                default=Decimal("3"),
                help_text="Максимальное значение: 999999,99",
                max_digits=10,
                verbose_name="Цена за минуту ожидания",
            ),
        ),
    ]
